### ISSUE TITLE
Sorting does not work correctly on progress page

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#90] opened 2019-02-24 00:23 UTC
In particular, sorting does not work correctly for rows that are modified after the page has been loaded. I have a screenshot as an example, and I will send it to you privately upon request.

**Comment by dlareau** [comment] 2019-02-24 15:02
I have found and fixed a bug (bc0ac34) that meant the number of solved puzzles next to the team's name didn't update after the page has been loaded, but after playing around a bit, sorting does seem to work even after a number of different solves. 

If you have a screenshot that shows a failed sorting that isn't related to the number next to the team's names (as in a row with more green boxes below a row with fewer green boxes) please send it to me at jlareau@andrew.

**Comment by sam-yeom** [comment] 2019-02-24 19:15
I sent a screenshot to the Andrew email address that shows that sorting by puzzle solve time does not work correctly.

**Comment by dlareau** [comment] 2019-03-02 00:11
Fixed in b60f1ae, was caused by not updating the unix time for new AJAX data despite updating the visible time.

**Closed as completed by dlareau** 2019-03-02 00:11 UTC
Labels: bug, Easy
